version: '2'
services:
  frps:
    image: chaoyuechen/frps:latest
    command: /app/frp/frps -c /app/frp/frps.ini
    ports:
      - 7000:7000
      - 7500:7500
      - 50001:50001
      - 50002:50002
      - 50003:50003
      - 50004:50004
      - 50005:50005
    restart: always
    volumes:
      - ./frps.ini:/app/frp/frps.ini
      - ./frps.log:/app/frp/frps.log
